### PR TITLE
Add option to disable piezo

### LINKED ISSUE #15: Pin 25 is not possible to switch to INPUT
Piezzo hold pin 25 as OUTPUT permanently.

### PR DESCRIPTION
**Pull request by Tasssadar**
Closes #15

### CODE REVIEW

**Review by JarekParal — APPROVED** [review]

**Comment by JarekParal** [comment]
I think that the code is good. I can just suggest adding a warning message to [documentation](https://github.com/RoboticsBrno/RB3201-RBControl-library/pull/17/files#diff-9a0520d22449c90100af1222d51e7766R31):
`Warning: disabling the piezo is not recommanded due to turn off low battery/power voltage sound indicator`.

**Comment by JarekParal** [comment]
The code is in my opinion good. I

**Comment by cednik** [comment]
Reopened because of adding warning @JarekParal ?

**Comment by JarekParal** [comment]
I didn't want to close this pull-request. It was a mistake.

**Pull request merged**
